---

name: Differential ShellCheck
description: Differential ShellCheck

branding:
  icon: check-circle
  color: green

inputs:
  base:
    description: Repository base
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  head:
    description: Head of changes
    required: true
    default: ${{ github.event.pull_request.head.sha }}
  ignored-codes:
    description: List of ShellCheck codes which should be excluded from validation
    deprecationMessage: This option is now deprecated, please consider using `.shellcheckrc` instead.
    required: false
  shell-scripts:
    description: List of Shell scripts proposed for validation
    required: false
  external-sources:
    description: |
      Enable following of source statements even when the file is not specified as input. By default, shellcheck will only follow files specified on the command-line (plus /dev/null).
      This option allows following any file the script may source. This option may also be enabled using external-sources=true in .shellcheckrc. This flag takes precedence.
    default: 'true'
    required: false
  severity:
    description: Specify minimum severity of errors to consider. Valid values in order of severity are error, warning, info and style. The default is style.
    default: style
    required: false
  token:
    description: GitHub TOKEN used to upload SARIF data
    required: false

runs:
  using: composite
  steps:
    - id: core
      name: Run Differential ShellCheck Core
      uses: ./core
      with:
        base: ${{ inputs.base }}
        head: ${{ inputs.head }}
        ignored-codes: ${{ inputs.ignored-codes }}    # <-- Deprecated option
        shell-scripts: ${{ inputs.shell-scripts }}
        external-sources: ${{ inputs.external-sources }}
        severity: ${{ inputs.severity }}
        token: ${{ inputs.token }}

    - if: ${{ always() }}
      name: Upload artifact with defects in SARIF format
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
      with:
        name: defects.sarif
        path: defects.sarif
        retention-days: 7

    - if: ${{ inputs.token && always() }}
      name: Upload SARIF
      uses: github/codeql-action/upload-sarif@807578363a7869ca324a79039e6db9c843e0e100
      with:
        sarif_file: defects.sarif
        category: ShellCheck
        token: ${{ inputs.token }}
